CXXFLAGS := -std=c++23 -lGL -lGLU -lglut


all: 10.point 20.line 21.line 22.line-stipping 30.triangle 31.triangle-strip 35.quad-stipping 40.scissor 50.stencil 60.custom-chip

10.point:

20.line:
21.line:
22.line-stipping:

30.triangle:
30.triangle-strip:

35.quad-stipping:

40.scissor:

50.stencil:

60.custom-chip:
