CXXFLAGS := -std=c++23 -I../libs/math3d/include -lGL -lGLU -lglut

all: 10.color-cube 20.ambient-light 30.light 40.normal 50.spot-light 60.shadow 70.reflection

10.color-cube:
20.ambient-light:
30.light:
40.normal:math3d
50.spot-light:
60.shadow:math3d
70.reflection:

math3d:
	g++ -c ${CXXFLAGS} -o $@ ../libs/math3d/src/math3d.cpp
